loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  limits_config:
    ingestion_rate_mb: 6
    ingestion_burst_size_mb: 8
  storage:
    type: 'filesystem'
singleBinary:
  replicas: 1
