apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
spec:
  config: |
    extensions:
      health_check:   
    receivers: 
      otlp:
        protocols:
          grpc:
          http:
      prometheus:
        config:
          global:
            scrape_interval: 60s
            scrape_timeout: 10s
          scrape_configs:
          - job_name: 'otel-collector'
            static_configs:
            - targets: ['0.0.0.0:8888']
      jaeger:
        protocols:
          grpc:
          thrift_binary:
          thrift_compact:
          thrift_http: 
    processors:
      batch:  
    exporters:
      logging:
    service:
      pipelines:
        traces:
          receivers: [otlp, jaeger]
          processors: [batch]
          exporters: [logging]
        metrics:
          receivers: [otlp, prometheus]
          processors: [batch]
          exporters: [logging]
      extensions: [health_check]
---
