apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: monitoring
spec:
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    
    exporters:
      loki:
        endpoint: http://loki-gateway/loki/api/v1/push
        tls:
          insecure: true
      prometheus:
        endpoint: ':59090'
      otlp:
        endpoint: tempo:4317
        tls:
          insecure: true
    
    extensions:
      zpages:
    
    service:
      extensions: [zpages]
      pipelines:
        logs:
          receivers: [otlp]
          exporters: [loki]
        metrics:
          receivers: [otlp]
          exporters: [prometheus]
        traces:
          receivers: [otlp]
          exporters: [otlp]
  ports:
    - name: otel-zpages
      port: 55679
      targetPort: 55679
