apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: monitoring
spec:
  config: |
    receivers:
      loki/promtail:
        protocols:
          http:
        use_incoming_timestamp: true
      otlp:
        protocols:
          grpc:
          http:
    
    processors:
      attributes/logs:
        actions:
        - action: insert
          key: loki.attribute.labels
          value: namespace, container, pod, job
        - action: insert
          key: loki.format
          value: raw
      transform/metrics:
        metric_statements:
          - context: datapoint
            statements:
            - set(attributes["svc"], resource.attributes["service.name"])
    
    exporters:
      loki:
        endpoint: http://loki-gateway/loki/api/v1/push
        tls:
          insecure: true
      prometheus:
        endpoint: ':59090'
      otlp:
        endpoint: tempo:4317
        tls:
          insecure: true
    
    extensions:
      zpages:
    
    service:
      extensions: [zpages]
      pipelines:
        logs:
          receivers: [loki/promtail]
          processors: [attributes/logs]
          exporters: [loki]
        metrics:
          receivers: [otlp]
          processors: [transform/metrics]
          exporters: [prometheus]
        traces:
          receivers: [otlp]
          exporters: [otlp]
  ports:
    - name: otel-zpages
      port: 55679
      targetPort: 55679
    - name: otel-loki
      port: 3500
      targetPort: 3500
