# default namespace

# cluster issuers
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: pgj646@gmail.com
    privateKeySecretRef:
      name: letsencrypt-issuer-staging-key
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: pgj646@gmail.com
    privateKeySecretRef:
      name: letsencrypt-issuer-prod-key
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx
---
