apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: monitoring
spec:
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    
    exporters:
      otlp:
        endpoint: tempo:4317
        tls:
          insecure: true
    
    extensions:
      zpages:
        endpoint: localhost:55679
    
    service:
      extensions: [zpages]
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [otlp]
        
  ports:
    - name: otel-zpages
      port: 55679
      targetPort: 55679
---
