# portal namespace
apiVersion: v1
kind: Namespace
metadata:
  name: portal
  labels:
    name: portal
---

# portal web
apiVersion: v1
kind: ConfigMap
metadata:
  name: portalweb-config
  namespace: portal
data:
  env.js: >
    window.__env = {
      apiUrl: 'http://localhost:30701',
    };
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portalweb-deploy
  namespace: portal
  labels:
    app: portalweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portalweb
  template:
    metadata:
      labels:
        app: portalweb
    spec: 
      containers:
      - name: portalweb-pod
        image: ne1410s/portalweb:0.0.1-alpha
        ports:
        - containerPort: 80
        volumeMounts:
        - name: portalweb-volume
          mountPath: /usr/share/nginx/html/assets
      volumes:
      - name: portalweb-volume
        configMap:
          name: portalweb-config
---
apiVersion: v1
kind: Service
metadata:
  name: portalweb-nodeport
  namespace: portal
spec:
  type: NodePort
  selector:
    app: portalweb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30700
---
