apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: monitoring
spec:
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    
    exporters:
      # prometheus:
        # endpoint: prometheus-service:8080
      otlp:
        endpoint: tempo:4317
        tls:
          insecure: true
      loki:
        endpoint: http://loki-gateway/loki/api/v1/push
        tls:
          insecure: true
    
    extensions:
      zpages:
        endpoint: localhost:55679
    
    service:
      extensions: [zpages]
      pipelines:
        # metrics:
          # receivers: [otlp]
          # exporters: [prometheus]
        traces:
          receivers: [otlp]
          exporters: [otlp]
        logs:
          receivers: [otlp]
          exporters: [loki]
          
  ports:
    - name: otel-zpages
      port: 55679
      targetPort: 55679
---
